### ISSUE TITLE
Metadata files contain absolute paths

### ISSUE THREAD

**Issue by Michael-F-Bryan** [wasmerio/cargo-wapm#18]
It looks like when `cargo-wapm` generates the `wapm.toml`, it uses absolute paths for things like the `README` rather than making them relative to the base directory.

Here is one example:

```toml
[package]
name = "aysjha/sgp3"
version = "0.1.5"
description = "sgp4 for wasm, published on WAPM"
license = "MIT OR Apache-2.0"
readme = "/Users/ayushjha/git/wasmer/sgp4/README.md"
```

This used to work previously because we never did any validation on the manifest and `wapm2pirita` blindly copied *everything* from the package directory into the `*.tar.gz` file that gets published, whereas newer versions are more selective in what they upload.

@ayys this is why we're seeing a bunch of failures at the moment.
